# Setup Docker Hub
# ansible-playbook -i ./inventory/pubdevvm docker-hub.yml --extra-vars "env=pubdevvm"

- hosts: "{{env}}"
  user: user
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - { role: docker-hub, when: ansible_os_family == "Debian" }
    - { role: docker-hub-centos, when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat" }
